### ISSUE TITLE
Twitter HPACK

### ISSUE THREAD

**Issue by jgauffin** [ringostarr80/hpack#1]
Isn't this just a straight conversion of the Twitter hpack library? You can't just replace the copyright notices.

**Comment by ringostarr80** [comment]
Yes, it's a straight conversion of the twitter hpack library. Should or must I add something to the copyright notices? I've copied the "LICENCE" file and added a "NOTICE" file where I added the information, that this is a conversion of the twitter library.

**Comment by jgauffin** [comment]
My issue is that you replaced the original copyright notice in every file with your own name. A port is just Derivative work, so this clause applies:

> You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and

Thus, you cannot remove Twitters copyright notices from the files.

The license also states:

> You must cause any modified files to carry prominent notices stating that You changed the files; and

I don't know how you are supposed to do that. I asked a question here: http://opensource.stackexchange.com/questions/2794/project-port-to-another-language-dealing-with-copyright-notices-when-using-ap

**Comment by ringostarr80** [comment]
Ok, I think I understand the problem. So, how should I change the copyright notices?

something like this:

```
/*
 * Copyright 2014 Twitter, Inc
 * This file is a derivative work modified by Ringo Leese
 * 
 * Licensed under...
...
 */
```
