### ISSUE TITLE
name CopyTo makes no sense

### ISSUE THREAD

**Issue by zgabi** [ringostarr80/hpack#2]
The following 2 lines:
https://github.com/ringostarr80/hpack/blob/44e9552e8b7088ce25883bbb063cf63d6c4055d9/Encoder.cs#L406-L407

Was:
https://github.com/twitter/hpack/blob/d58ac0c4dff6a228c4f93a8b31587392918a7a8e/hpack/src/main/java/com/twitter/hpack/Encoder.java#L339-L340

In the original Java code.

Currently the 2 C# line makes no sense, since it copes the bytes from the source to the same target array.

I don't know whether it is causeing any problem or not, but you probably you wanted to write:
`name = name.ToArray(); `
or similar.

**Comment by ringostarr80** [comment]
Thank you for reporting and excuses for being so late.

I've fixed it.
